package io.tatum.model.response.btc;

import java.math.BigDecimal;

/**
 *
 * @export
 * @interface BtcTxInputs
 */
public interface IBtcTxInputs {

    /**
     *
     * @type {BtcTxPrevout}
     * @memberof BtcTxInputs
     */
    IBtcTxPrevout getPrevout();
    void setPrevout(IBtcTxPrevout prevout);

    /**
     * Data generated by a spender which is almost always used as variables to satisfy a pubkey script.
     * @type {string}
     * @memberof BtcTxInputs
     */
    String getScript();
    void setScript(String script);

    /**
     * Transaction witness.
     * @type {string}
     * @memberof BtcTxInputs
     */
    String getWitness();
    void setWitness(String witness);

    /**
     *
     * @type {number}
     * @memberof BtcTxInputs
     */
    BigDecimal getSequence();
    void setSequence(BigDecimal sequence);

    /**
     *
     * @type {BtcTxCoin}
     * @memberof BtcTxInputs
     */
    IBtcTxCoin getCoin();
    void setCoin(IBtcTxCoin coin);
}
